---
- name: Set up compute node
  hosts: compute_nodes
  sudo: True

  tasks:
  - name: ensure nova-compute packages are installed
    apt: pkg=$item update-cache=yes
    with_items:
      - nova-compute-qemu

  - name: ensure nova.conf file is present
    template: >
          src=templates/etc/nova/nova.conf
          dest=/etc/nova/nova.conf
          owner=nova group=nova mode=0600
          backup=yes
    notify:
      - restart nova-compute
      
  - name: ensure nova-compute.conf present
    copy: >
        src=files/etc/nova/nova-compute.conf
        dest=/etc/nova/nova-compute.conf
        owner=nova group=nova mode=0600
        backup=yes
    notify:
      - restart nova-compute

  - name: ensure /etc/libvirt/qemu.conf is correct
    copy: >
        src=files/etc/libvirt/qemu.conf
        dest=/etc/libvirt/qemu.conf
        owner=root group=root mode=0644
        backup=yes
    notify:
      - restart libvirt

  handlers:
  - name: restart nova-compute
    service: name=nova-compute state=restarted

  - name: restart libvirt
    service: name=libvirt-bin state=restarted
