---
- name: Nova controller services
  hosts: controller
  sudo: True
  gather_facts: True
  tasks:

  - name: ensure nova database is present
    mysql_db: name=nova
    
  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/setting-up-sql-database-mysql.html
  - name: ensure nova database user is present
    mysql_user: name=nova host=$item password=$nova_db_password priv=nova.*:ALL
    with_items:
      - '%'
      - localhost
 
    # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/installing-the-cloud-controller.html
  - name: ensure nova packages are installed
    apt: pkg=$item
    with_items:
      - rabbitmq-server
      - nova-novncproxy
      - novnc
      - nova-api
      - nova-ajax-console-proxy
      - nova-cert
      - nova-consoleauth
      - nova-scheduler
      - nova-conductor


  - name: ensure api-paste.ini is present
    copy: src=files/etc/nova/api-paste.ini dest=/etc/nova/api-paste.ini owner=nova group=nova mode=0660 backup=yes

  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/compute-minimum-configuration-settings.html
  - name: ensure nova.conf file is present
    template: src=templates/etc/nova/nova.conf dest=/etc/nova/nova.conf owner=nova group=nova mode=0660 backup=yes

  - name: ensure services are stopped
    service: name=$item state=stopped
    with_items:
      - nova-api
      - nova-conductor
      - nova-scheduler
      - nova-novncproxy
      - nova-consoleauth
      - nova-cert

  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/compute-db-sync.html
  - name: ensure database is synced
    command: /usr/bin/nova-manage db sync

  - name: ensure services are started
    service: name=$item state=started
    with_items:
      - nova-api
      - nova-conductor
      - nova-scheduler
      - nova-novncproxy
      - nova-consoleauth
      - nova-cert
      - rabbitmq-server

  - name: ensure rabbitmq starts after virtualbox additions at boot (1/2)
    file: dest=/etc/rc2.d/S20rabbitmq-server state=absent
    when_string: $ansible_bios_version == "VirtualBox"

  - name: ensure rabbitmq starts after virtualbox additions at boot (2/2)
    file: src=/etc/init.d/rabbitmq-server dest=/etc/rc2.d/S95rabbitmq-server state=link
    when_string: $ansible_bios_version == "VirtualBox"
