---
- name: Quantum L3, DHCP, LBaaS and metadata agents
  hosts: netnode
  sudo: True

  tasks:
  - name: ensure udev rule to configure br-ex is in place
    copy: >
          src=files/etc/udev/rules.d/configure_br-ex.rules
          dest=/etc/udev/rules.d/configure_br-ex.rules
          owner=root group=root mode=0644

  - name: ensure udev script for br-ex is present
    template: >
          src=templates/etc/udev/configure_br-ex
          dest=/etc/udev/configure_br-ex
          owner=root group=root mode=0755

  - name: ensure ovs bridge for gateway br-ex present
    command: /usr/bin/ovs-vsctl -- --may-exist add-br br-ex

  - name: ensure br-ex has eth3 enslaved
    command: /usr/bin/ovs-vsctl -- --may-exist add-port br-ex $ext_net_nic

  - name: install the packages
    apt: name=$item
    with_items:
      - quantum-l3-agent
      - quantum-dhcp-agent
      - quantum-lbaas-agent
      - quantum-metadata-agent

  - name: ensure quantum.conf ok
    template: >
          src=templates/etc/quantum/quantum.conf
          dest=/etc/quantum/quantum.conf
          owner=quantum group=quantum mode=0660 backup=yes
    notify:
      - restart l3 agent
      - restart dhcp agent
      - restart lbaas agent
      - restart metadata agent

    # note: default lbaas_agent.ini works

  - name: ensure l3 agent is configured
    template: >
          src=templates/etc/quantum/l3_agent.ini
          dest=/etc/quantum/l3_agent.ini
          owner=quantum group=quantum mode=0660 backup=yes
    notify: restart l3 agent

  - name: ensure metadata agent is configured
    template: >
          src=templates/etc/quantum/metadata_agent.ini.j2
          dest=/etc/quantum/metadata_agent.ini
          owner=quantum group=quantum mode=0660 backup=yes
    notify: restart metadata agent

  handlers:
    - name: restart l3 agent
      action: service name=quantum-l3-agent state=restarted

    - name: restart dhcp agent
      action: service name=quantum-dhcp-agent state=restarted

    - name: restart lbaas agent
      action: service name=quantum-lbaas-agent state=restarted

    - name: restart metadata agent
      action: service name=quantum-metadata-agent state=restarted
